name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: us.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: unit tests
      run: make unit-tests
    - name: integration tests
      run: make integration-tests
    - name: helm chart tests
      working-directory: charts/rabbitmq
      run: ./test.sh
