name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: us.gcr.io/cf-rabbitmq-for-k8s-bunny/rabbitmq-for-kubernetes-ci
    steps:
      - name: print
        run: echo Hello "$MY_SECRET" and "$JSON_SECRET"
        env:
          MY_SECRET: ${{ secrets.SECRET1 }}
          JSON_SECRET: ${{ secrets.SECRET2 }}
    # - name: Check out code into the Go module directory
      # uses: actions/checkout@v2
    # - name: Unit tests
      # run: make unit-tests
    # - name: Integration tests
      # run: make integration-tests
    # - name: Helm chart tests
      # working-directory: charts/rabbitmq
      # run: ./test.sh
